name: 'taxi_platform'
version: '1.0.0'
config-version: 2

profile: 'taxi_platform'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  taxi_platform:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts